spring.application.name=email
server.port=8082


spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.url=jdbc:postgresql://localhost:5432/ms-email
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.addresses=amqps://wgdfzcxs:N0Qg0-5f7eNRKH0pqx1_iraNxvAXMMb_@beaver.rmq.cloudamqp.com/wgdfzcxs

 broker.queue.email.name=default.email


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seu_email
spring.mail.password=sua_senha_app
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

## para criar uma senha de app
## https://support.google.com/accounts/answer/185833
